name: Deploy to Skynet

on:
  push:
    branches: [main]

jobs:
  build:
        with:
          upload-dir: ./
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.REGISTRY_SEED || '' }}
